import { ThemeConfig } from 'antd';
// import {
//   BODY_BACKGROUND,
//   BORDER,
//   DARK_MODE,
//   GRAY_SCALE,
//   THEME_COLOR,
// } from './color';
import { AliasToken, OverrideToken } from 'antd/es/theme/interface';

export function rgba(hex: string, opacity = 1) {
  if (!/^#([A-Fa-f0-9]{3}){1,2}$/.test(hex)) {
    throw new Error('Invalid Hex');
  }

  const decimal = parseInt(hex.substring(1), 16);

  const r = (decimal >> 16) & 255;
  const g = (decimal >> 8) & 255;
  const b = decimal & 255;

  return `rgba(${r}, ${g}, ${b}, ${opacity})`;
}

export const baseTheme: Partial<AliasToken> = {
  //Gobal Token spacing only here
  fontFamily: 'Be Vietnam Pro',
  fontWeightStrong: 500,
};

const getBaseComponentThemeConfig = ({
  components,
}: Pick<ThemeConfig, 'components'>): OverrideToken => {
  //Component Token spacing and common styles for both light theme and dark theme
  return {
    ...components,

    Alert: {
      ...components?.Alert,
      fontSize: 12,
      borderRadius: 6,
      defaultPadding: 4,
      fontWeightStrong: 700,
    },
    Avatar: {
      ...components?.Avatar,
      containerSizeSM: 20,
      textFontSizeSM: 8.5,
    },
    Breadcrumb: {
      // colorTextDescription: GRAY_SCALE.GRAY_LIGHT,
      // colorText: baseTheme.colorPrimary,
      colorBgTextHover: 'transparent',
      fontSize: 24,
      fontWeightStrong: 700,
      separatorMargin: 10,
    },
    Button: {
      ...components?.Button,
      paddingInlineSM: 12,
      paddingBlockSM: 8,
      paddingInline: 12,
      paddingBlock: 10,
      paddingInlineLG: 24,
      paddingBlockLG: 8,
      contentFontSizeSM: 14,
      contentFontSize: 14,
      contentFontSizeLG: 14,
      borderRadiusSM: 8,
      fontWeight: 500,
      borderRadius: 8,
      controlHeightSM: 26,
      controlHeight: 36,
      controlHeightLG: 36,
      defaultShadow: '0',
      primaryShadow: '0',
      marginXS: 12,
      lineWidth: 1.2,
    },
    Calendar: {
      ...components?.Calendar,
      fontSize: 12,
    },
    Card: {
      // colorTextHeading: GRAY_SCALE.GRAY_DARK,
      ...components?.Card,
      borderRadiusLG: 16,
      paddingLG: 16,
      marginLG: 0,
    },
    Checkbox: {
      ...components?.Checkbox,
      lineWidth: 2,
      borderRadiusSM: 4,
    },
    DatePicker: {
      ...components?.DatePicker,
      controlHeightSM: 30,
      borderRadius: 8,
      lineWidthBold: 0,
      fontSize: 14,
      inputFontSizeSM: 12,
      lineHeight: 0,
    },
    Divider: {
      ...components?.Divider,
      paddingLG: 16,
    },
    Dropdown: {
      ...components?.Dropdown,
      controlPaddingHorizontal: 12,
      controlHeight: 32,
      borderRadiusLG: 12,
      paddingBlock: 8,
      padding: 8,
      borderRadius: 8,
      borderRadiusSM: 8,
      fontWeightStrong: 500,
      paddingXXS: 6,
    },
    FloatButton: {
      ...components?.FloatButton,
      controlHeightLG: 64,
      fontSizeIcon: 20,
    },
    Form: {
      ...components?.Form,
      labelFontSize: 14,
      fontSize: 14,
      marginLG: 24,
      lineHeight: 1.5,
      verticalLabelPadding: '0 0 16px',
      fontWeightStrong: 500,
    },
    Input: {
      ...components?.Input,
      paddingBlock: 11,
      paddingInline: 16,
      controlHeight: 42,
      borderRadius: 8,
      borderRadiusSM: 8,
      inputFontSize: 14,
      fontWeightStrong: 500,
      lineHeight: 1.43,
    },
    InputNumber: {
      ...components?.InputNumber,
      paddingBlock: 11,
      paddingInline: 16,
      controlHeight: 42,
      borderRadius: 8,
      borderRadiusSM: 8,
      inputFontSize: 14,
      fontWeightStrong: 500,
      lineHeight: 1.43,
    },
    Layout: {
      ...components?.Layout,
      // colorBgBody: BODY_BACKGROUND,
      // colorBgHeader: GRAY_SCALE.WHITE,
      headerPadding: 0,
      headerHeight: 0,
    },
    Modal: {
      ...components?.Modal,
      titleFontSize: 16,
      titleLineHeight: 1,
      fontWeightStrong: 500,
      borderRadiusLG: 16,
      marginXS: 0,
    },
    Menu: {
      ...components?.Menu,
      colorActiveBarHeight: 0,
      colorActiveBarWidth: 3,
      // colorItemTextSelectedHorizontal: 'transparent',
      // colorItemTextHover:'red',
      // colorItemTextSelected: 'red',
      // colorItemBgSelected: rgba(baseTheme.colorPrimary, 0.1),
      radiusItem: 0,
      colorSubItemBg: 'transparent',
      itemMarginInline: 5,
      itemMarginBlock: 5,
      itemPaddingInline: 24,
      controlHeightLG: 40,
      controlHeightSM: 22,
      padding: 16,
      paddingLG: 40,
      paddingSM: 40,
      borderRadiusLG: 12,
      subMenuItemBorderRadius: 8,
    },
    Message: {
      ...components?.Message,
      fontSize: 14,
    },
    Popover: {
      ...components?.Popover,
      borderRadiusLG: 12,
      sizePopupArrow: 0,
      lineHeight: 1.5,
      titleMinWidth: 0,
      padding: 16,
    },
    Pagination: {
      ...components?.Pagination,
      //   paginationItemSize: 30,
      //   borderRadius: '50%',
      // colorBgContainer: baseTheme.colorPrimary,
      // colorPrimary: GRAY_SCALE.WHITE,
      // colorPrimaryHover: GRAY_SCALE.WHITE,
      colorBgContainer: 'transparent',
      fontWeightStrong: 700,
      fontSize: 14,
      margin: 0,
    },
    Radio: {
      ...components?.Radio,
      wrapperMarginInlineEnd: 16,
      fontSize: 16,
      fontWeightStrong: 500,
    },
    // colorPrimaryBorder: rgba(baseTheme.colorPrimary, 0.8),
    // colorPrimaryBorderHover: baseTheme.colorPrimary,
    Segmented: {
      ...components?.Segmented,
      trackPadding: 8,
      borderRadius: 12,
      borderRadiusSM: 8,
      fontSize: 16,
      controlHeight: 42,
    },
    Select: {
      ...components?.Select,
      //   paddingXXS: '4px 0px',
      // controlHeightSM: 30,
      // controlItemBgActive: rgba(baseTheme.colorPrimary, 0.1),
      controlPaddingHorizontal: 16,
      controlHeight: 44,
      borderRadius: 8,
      fontSize: 14,
      multipleItemHeight: 34,
      paddingSM: 17,
      zIndexPopup: 999,
    },
    Switch: {
      ...components?.Switch,
      // handleBg: '#fff',
      colorTextQuaternary: 'rgba(0, 0, 0, 0.25)',
    },
    Typography: {
      ...components?.Typography,
      fontSizeHeading1: 24,
      fontSizeHeading2: 20,
      fontSizeHeading3: 18,
      fontSizeHeading4: 16,
      fontSizeHeading5: 12,
      fontSize: 14,
      lineHeightLG: 1,
      lineHeightSM: 1,
      lineHeightHeading1: 1.3,
      lineHeightHeading2: 1.2,
      lineHeightHeading3: 1.2,
      lineHeightHeading4: 1.2,
      lineHeightHeading5: 1.2,
      lineHeight: 1.2,
      titleMarginBottom: 0,
      titleMarginTop: 0,
      marginXS: 0,
      marginXXS: 0,
      paddingSM: 0,
    },
    Table: {
      ...components?.Table,
      fontWeightStrong: 600,
      fontSize: 14,
      padding: 17,
      borderRadius: 0,
      stickyScrollBarBorderRadius: 0,
      // colorText: GRAY_SCALE.GRAY,
      //   tableHeaderBg: 'transparent',
      // colorBgContainer:''
    },
    TreeSelect: {
      controlHeightSM: 24,
    },
    Tabs: {
      ...components?.Tabs,
      fontFamily: 'DM Sans',
      paddingLG: 24,
      titleFontSize: 14,
      margin: 24,
      horizontalItemGutter: 24,
      marginSM: 8,
      horizontalItemPadding: '10px 0px',
    },
    Tooltip: {
      //   colorBgDefault: rgba(GRAY_SCALE.DARK, 0.75),
      controlHeight: 32,
    },
    Timeline: {
      lineType: 'dashed',
    },
    Tag: {
      ...components?.Tag,
      lineHeight: 1,
      marginXS: 0,
      borderRadiusSM: 8,
      fontSizeSM: 12,
      controlHeight: 42,
    },
  };
};

export const lightTheme: ThemeConfig = {
  token: {
    ...baseTheme,
    // Light theme Global Token colors only
    colorPrimary: '#338379',
    colorLink: '#2B2D42',
    colorLinkHover: '#338379',
    colorText: '#2B2D42',
    colorTextDescription: '#A3AED0',
    boxShadowSecondary: '0px 5px 15px 0px #E1E1E1',
    colorBorder: '#EEEFF2',
    colorError: '#DA0E0E',
    colorErrorHover: '#DA0E0E',
    colorIcon: '#999999',
    colorIconHover: '#333333',
    colorTextDisabled: '#858585',
  },
  cssVar: true,

  components: getBaseComponentThemeConfig({
    components: {
      Alert: {
        colorErrorBg: '#FDECEA',
        colorErrorBorder: '#D32F2F',
        colorText: '#D32F2F',
      },
      Avatar: {
        colorTextLightSolid: '#FFF',
        groupBorderColor: '#FFF',
        colorTextPlaceholder: '#0E77DA',
      },
      Breadcrumb: {
        itemColor: '#A3AED0',
        colorText: '#A3AED0',
        separatorColor: '#A3AED0',
        linkHoverColor: '#338379',
        lastItemColor: '#2B2D42',
      },
      Button: {
        defaultBorderColor: '#E3E8E7',
        defaultColor: '#5E716B',
        defaultBg: 'transparent',
        lineWidth: 1.5,
        defaultHoverColor: '#2f3836',
        defaultHoverBg: 'transparent',
        defaultHoverBorderColor: '#E3E8E7',
        defaultActiveBg: 'transparent',
        // defaultHoverBorderColor: 'transparent',
        colorPrimary: '#006458',
        colorPrimaryHover: '#338379',
        colorPrimaryActive: '#338379',
        colorLink: '#338379',
        textHoverBg: '#F4F2FF',
        borderColorDisabled: '#99C1BC',
        colorBgContainerDisabled: '#99C1BC',
        colorTextDisabled: '#FFFFFF',
        colorError: '#DA0E0E',
        boxShadow: 'none',
      },
      Card: {
        colorBgContainer: '#fff',
        colorBorderSecondary: '#E3E8E7',
        colorBorder: '#E3E8E7',
        boxShadowTertiary: 'none',
      },
      Checkbox: {
        colorBorder: '#5E716B',
        colorPrimary: '#338379',
        // colorPrimaryHover: 'lightgray',
        // colorPrimaryBorder: '#338379',
        // colorPrimaryBorderHover: '#338379',
        colorWhite: '#fff',
        colorBgContainer: '#FFF',
        colorText: '#5E716B',
      },
      DatePicker: {
        colorTextPlaceholder: '#F8F8F8',
        colorBgContainer: '#fff',
        cellHoverBg: '',
        colorBgElevated: '#fff',
        colorText: '#5E716B',
        colorBorder: '#E3E8E7',
        activeShadow: 'none',
      },
      Dropdown: {
        controlItemBgActiveHover: '#F8F8F8',
        controlItemBgHover: '#F8F8F8',
        controlItemBgActive: '#F8F8F8',
        colorBgElevated: '#fff',
      },
      FloatButton: {
        colorBgElevated: '#A3AED0',
        colorText: '#fff',
        boxShadowSecondary: '0px 5px 15px 0px #E1E1E1',
        colorPrimaryHover: '#338379',
        colorFillContent: '#6946FF',
      },
      Form: {
        labelColor: '#5E716B',
        colorError: '#DA0E0E',
      },
      Input: {
        colorTextPlaceholder: '#C8D1CF',
        colorBgContainer: '#fff',
        colorText: '#2F3836',
        activeShadow: 'none',
        paddingXXS: 12,
      },
      InputNumber: {
        colorTextPlaceholder: '#C8D1CF',
        colorBgContainer: '#fff',
        colorText: '#2F3836',
        activeShadow: 'none',
        paddingXXS: 12,
      },
      Layout: {
        colorBgBody: '#FFF',
        headerBg: '#fff',
        colorTextPlaceholder: '#C8D1CF',
        // colorBgHeader: DARK_MODE.BG_COLOR,
      },
      Modal: {
        contentBg: '#fff',
        headerBg: '#fff',
        titleColor: '#2F3836',
        colorBgMask: 'rgba(227, 232,231,.3)',
      },
      Menu: {
        colorItemBg: '#FFF',
        colorItemTextHover: '#338379',
        itemColor: '#758D86',
        itemHoverColor: '#338379',
        popupBg: '#FFF',
        itemSelectedBg: '#338379',
        itemActiveBg: '#338379',
        colorSplit: 'none',
        itemSelectedColor: '#338379',
        horizontalItemSelectedColor: '#338379',
        // colorItemBgSelected: rgba(baseTheme.colorPrimary, 0.1),
      },
      Message: {
        contentBg: '#FFF',
        colorError: '#DA0E0E',
        colorInfo: '#338379',
        colorSuccess: '#0caf60',
        colorText: '#2B2D42',
        colorWarning: '#fe964a',
      },
      Popover: {
        colorBgElevated: '#fff',
      },
      Pagination: {
        colorPrimary: '#338379',
        colorBorder: '',
      },
      Progress: {
        defaultColor: '#338379',
        remainingColor: '#EFFFFD',
      },
      Radio: {
        colorBorder: '#858585',
        dotSize: 7,
        colorBgContainer: '#FFF',
        colorPrimary: '#338379',
      },
      Segmented: {
        itemSelectedBg: '#F4F2FF',
        itemHoverBg: '#FFF',
        itemHoverColor: '#338379',
        itemActiveBg: '#fff',
        trackBg: '#fff',
        itemColor: '#2B2D42',
        itemSelectedColor: '#338379',
      },
      Select: {
        colorTextPlaceholder: '#C8D1CF',
        colorText: '#2F3836',
        colorBgContainer: '#fff',
        colorBgElevated: '#fff',
        multipleItemBg: '#F8F8F8',
        optionSelectedBg: '#F8F8F8',
        optionActiveBg: '#F8F8F8',
        colorTextQuaternary: '#2F3836',
        optionSelectedColor: '#338379',
        activeOutlineColor: 'none',
      },
      Table: {
        // rowHoverBg: '#F4F2FF',
        rowHoverBg: '#F5FBFF',
        headerColor: '#5E716B',
        headerBg: '#F8F8F8',
        borderColor: 'transparent',
        colorBgContainer: '#fff',
        colorText: '#2F3836',
        stickyScrollBarBg: '#E3E8E7',
        headerSplitColor: '#F8F8F8',
        colorSplit: 'transparent',
      },
      Tabs: {
        itemActiveColor: '#338379',
        colorText: '#5E716B',
        cardBg: '#fff',
        colorBgBase: '#fff',
        colorBorderSecondary: '#E3E8E7',
      },
      Tag: {
        defaultBg: '#FFF',
        defaultColor: '#2B2D42',
      },
      Typography: {
        colorSuccess: '#2A9240',
        colorError: '#DA0E0E',
        colorErrorActive: '#DA0E0E',
        colorLink: '#0C8CE9',
        colorLinkActive: '#0C8CE9',
        colorLinkHover: '#009DFF',
        colorTextDisabled: '#2B2D42',
        colorTextDescription: '#2B2D42',
      },
      Upload: {
        colorFillAlter: '#FFF',
      },
    },
  }),
};

export const darkTheme: ThemeConfig = {
  token: {
    ...baseTheme,
    // Dark theme Global Token colors only
    colorPrimary: '#246CF9',
    colorLink: '#009DFF',
    colorLinkHover: '#246CF9',
    colorText: '#F7F7F7',
    colorTextDescription: '#B0B0B0',
    boxShadowSecondary: '0px 5px 15px 0px rgba(0, 0, 0, 0.25)',
    colorBorder: '#232937',
    colorError: '#D32F2F',
    colorErrorHover: '#D32F2F',
    colorIcon: '#A3AED0',
    colorIconHover: '#F7F7F7',
    colorTextDisabled: '#858585',
  },
  cssVar: true,

  components: getBaseComponentThemeConfig({
    components: {
      Alert: {
        colorErrorBg: '#9B2727',
        colorErrorBorder: '#D32F2F',
        colorText: '#FEBDBD',
      },
      Avatar: {
        colorTextLightSolid: '#A3AED0',
        groupBorderColor: '#0D1426',
      },
      Breadcrumb: {
        itemColor: '#A3AED0',
        colorText: '#A3AED0',
        separatorColor: '#A3AED0',
        linkHoverColor: '#246CF9',
        lastItemColor: '#F7F7F7',
      },
      Button: {
        defaultBorderColor: '#DDD',
        defaultColor: '#F7F7F7',
        defaultBg: 'transparent',
        lineWidth: 1.5,
        defaultHoverColor: '#246CF9', //Primary color 2
        defaultHoverBg: 'transparent',
        defaultHoverBorderColor: '#DDD',
        defaultActiveBg: 'transparent',
        // defaultHoverBorderColor: 'transparent',
        colorPrimaryHover: '#246CF9',
        colorPrimaryActive: '#246CF9',
        colorLink: '#F7F7F7',
        textHoverBg: '#1F2C47',
        borderColorDisabled: 'transparent',
        colorBgContainerDisabled: '#D4D4D4',
        colorTextDisabled: '#1F2C47',
        colorError: '#D32F2F',

        // colorPrimary:'#fff',
        // colorPrimaryHover:'yellow'
      },
      Card: {
        colorBgContainer: '#151E31',
        colorBorderSecondary: '#232937',
        colorBorder: '#232937',
        boxShadowTertiary: 'none',
      },
      Checkbox: {
        colorBorder: '#858585',
        colorPrimary: '#246CF9',
        // colorPrimaryHover: 'lightgray',
        // colorPrimaryBorder: '#246CF9',
        // colorPrimaryBorderHover: '#246CF9',
        colorWhite: '#0D1426',
        colorBgContainer: '#151E31',
      },
      DatePicker: {
        colorTextPlaceholder: '#A3AED0',
        colorBgContainer: '#151E31',
        cellHoverBg: '',
        colorBgElevated: '#0D1426',
        colorText: '#F7F7F7',
        controlItemBgActive: '#246CF9',
      },
      Dropdown: {
        controlItemBgActiveHover: '#1F2C47',
        colorBgElevated: '#151E31',
        controlItemBgActive: '#1F2C47',
        controlItemBgHover: '#1F2C47',
      },
      FloatButton: {
        colorBgElevated: '#6472a0',
        colorText: '#F7F7F7',
        boxShadowSecondary: '0px 5px 15px 0px rgba(0, 0, 0, 0.25)',
        colorPrimaryHover: '#246CF9',
        colorFillContent: '#246CF9',
      },
      Form: {
        labelColor: '#F7F7F7',
        colorError: '#D32F2F',
      },
      Input: {
        colorTextPlaceholder: '#A3AED0',
        colorBgContainer: '#151E31',
        colorText: '#F7F7F7',
      },
      Layout: {
        colorBgBody: '#0D1426',
        headerBg: '#151E31',
        colorTextPlaceholder: '#A3AED0',
        // colorBgHeader: DARK_MODE.BG_COLOR,
      },
      Modal: {
        contentBg: '#151E31',
        headerBg: '#151E31',
        titleColor: '#F7F7F7',
      },
      Menu: {
        colorItemBg: '#151E31',
        colorItemTextHover: '#246CF9',
        itemColor: '#A3AED0',
        itemHoverColor: '#246CF9',
        popupBg: '#151E31',
        itemSelectedBg: '#1F2C47',
        itemActiveBg: '#1F2C47',
      },
      Message: {
        contentBg: '#151E31',
        colorError: '#D32F2F',
        colorInfo: '#246CF9',
        colorSuccess: '#42C882',
        colorText: '#F7F7F7',
        colorWarning: '#FE964A',
      },
      Popover: {
        colorBgElevated: '#151E31',
      },
      Pagination: {
        colorPrimary: '#246CF9',
        colorBorder: '',
      },
      Radio: {
        colorBorder: '#858585',
        dotSize: 7,
        colorBgContainer: '#151E31',
        colorPrimary: '#246CF9',
        buttonCheckedBg: 'red',
      },
      Segmented: {
        itemSelectedBg: '#1F2C47',
        itemHoverBg: '#151E31',
        itemHoverColor: '#246CF9',
        itemActiveBg: '#151E31',
        trackBg: '#151E31',
        itemColor: '#A3AED0',
        itemSelectedColor: '#246CF9',
      },
      Select: {
        colorTextPlaceholder: '#A3AED0',
        colorText: '#F7F7F7',
        colorBgContainer: '#151E31',
        colorBgElevated: '#151E31',
        multipleItemBg: '#151E31',
        optionSelectedBg: '#1F2C47',
        colorTextQuaternary: '#858585',
        optionSelectedColor: '#246CF9',
        optionActiveBg: '#1F2C47',
      },
      Table: {
        // rowHoverBg: '#F4F2FF',
        rowHoverBg: '#151E31',
        headerColor: '#A3AED0',
        headerBg: '#151E31',
        borderColor: '#232937',
        colorBgContainer: '#151E31',
        colorText: '#F7F7F7',
        stickyScrollBarBg: '#6d6d6d',
        headerSplitColor: '#151E31',
      },
      Tabs: {
        itemActiveColor: '#246CF9',
        colorText: '#A3AED0',
        cardBg: '#151E31',
        colorBgBase: '#151E31',
      },
      Tag: {
        defaultBg: '#151E31',
        defaultColor: '#F7F7F7',
      },
      Typography: {
        colorSuccess: '#2A9240',
        colorError: '#D32F2F',
        colorErrorActive: '#D32F2F',
        colorLink: '#009DFF',
        colorLinkActive: '#009DFF',
        colorLinkHover: '#009DFF',
        colorTextDisabled: '#858585',
        colorTextDescription: '#A3AED0',
      },
    },
  }),
};
